# Generated by Django 4.2.23 on 2025-06-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('CNH', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=11)),
            ],
        ),
    ]
